"""
SQLite database for the SMC trading bot.

Persists: trade history, signal log, event log, and settings.
Thread-safe via locking.
DB path: smc_bot/data/bot_data.db
"""

import os
import json
import sqlite3
import threading
from datetime import datetime, timezone, timedelta
from typing import List, Dict, Optional, Any

from utils.logger import get_logger

logger = get_logger("database")


class Database:
    """
    SQLite persistence layer.

    Tables:
        trades   — every order placed / closed
        signals  — every signal generated by the entry engine
        logs     — bot decision log (displayed on dashboard)
        settings — key-value configuration store

    Never deletes data. Always appends.
    """

    def __init__(self, db_path: Optional[str] = None) -> None:
        if db_path is None:
            db_path = os.path.join(
                os.path.dirname(os.path.abspath(__file__)),
                "bot_data.db",
            )
        self._db_path = db_path
        self._lock = threading.Lock()
        self._init_tables()
        logger.info(f"Database initialized: {self._db_path}")

    def _get_conn(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self._db_path, check_same_thread=False)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA journal_mode=WAL")
        return conn

    def _init_tables(self) -> None:
        with self._lock:
            conn = self._get_conn()
            try:
                conn.executescript("""
                    CREATE TABLE IF NOT EXISTS trades (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        ticket INTEGER,
                        symbol TEXT NOT NULL,
                        direction TEXT NOT NULL,
                        lot_size REAL NOT NULL,
                        entry_price REAL,
                        sl_price REAL,
                        tp1_price REAL,
                        tp2_price REAL,
                        close_price REAL,
                        pnl REAL DEFAULT 0,
                        rr_ratio REAL,
                        setup_score REAL,
                        setup_type TEXT,
                        status TEXT DEFAULT 'open',
                        session TEXT,
                        steps_log TEXT,
                        comment TEXT,
                        opened_at TEXT NOT NULL,
                        closed_at TEXT
                    );
                    CREATE TABLE IF NOT EXISTS signals (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        symbol TEXT NOT NULL,
                        direction TEXT NOT NULL,
                        entry_price REAL,
                        sl_price REAL,
                        tp1_price REAL,
                        tp2_price REAL,
                        rr_ratio REAL,
                        setup_score REAL,
                        setup_type TEXT,
                        confidence TEXT,
                        session TEXT,
                        executed INTEGER DEFAULT 0,
                        reason_rejected TEXT,
                        steps_log TEXT,
                        created_at TEXT NOT NULL
                    );
                    CREATE TABLE IF NOT EXISTS logs (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        level TEXT NOT NULL,
                        category TEXT,
                        symbol TEXT,
                        message TEXT NOT NULL,
                        details TEXT,
                        created_at TEXT NOT NULL
                    );
                    CREATE TABLE IF NOT EXISTS settings (
                        key TEXT PRIMARY KEY,
                        value TEXT NOT NULL,
                        updated_at TEXT NOT NULL
                    );
                    CREATE INDEX IF NOT EXISTS idx_trades_opened
                        ON trades(opened_at);
                    CREATE INDEX IF NOT EXISTS idx_trades_status
                        ON trades(status);
                    CREATE INDEX IF NOT EXISTS idx_signals_created
                        ON signals(created_at);
                    CREATE INDEX IF NOT EXISTS idx_logs_created
                        ON logs(created_at);
                """)
                conn.commit()
            finally:
                conn.close()

    # ── Trades ───────────────────────────────────────────────

    def log_trade(
        self, ticket: int, symbol: str, direction: str,
        lot_size: float, entry_price: float, sl_price: float,
        tp1_price: float, tp2_price: float = 0.0,
        setup_score: float = 0.0, setup_type: str = "",
        rr_ratio: float = 0.0, session: str = "",
        steps_log: Optional[Dict] = None, comment: str = "",
    ) -> int:
        """Insert a new trade record. Returns row id."""
        now = datetime.now(timezone.utc).isoformat()
        steps_json = json.dumps(steps_log) if steps_log else ""
        with self._lock:
            conn = self._get_conn()
            try:
                cur = conn.execute(
                    """INSERT INTO trades
                       (ticket,symbol,direction,lot_size,entry_price,
                        sl_price,tp1_price,tp2_price,setup_score,setup_type,
                        rr_ratio,session,steps_log,comment,opened_at,status)
                       VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'open')""",
                    (ticket, symbol, direction, lot_size, entry_price,
                     sl_price, tp1_price, tp2_price, setup_score, setup_type,
                     rr_ratio, session, steps_json, comment, now),
                )
                conn.commit()
                return cur.lastrowid
            finally:
                conn.close()

    def close_trade(self, ticket: int, close_price: float,
                    pnl: float) -> None:
        now = datetime.now(timezone.utc).isoformat()
        with self._lock:
            conn = self._get_conn()
            try:
                conn.execute(
                    """UPDATE trades SET status='closed',
                       close_price=?, pnl=?, closed_at=?
                       WHERE ticket=? AND status='open'""",
                    (close_price, pnl, now, ticket),
                )
                conn.commit()
            finally:
                conn.close()

    def sync_closed_trades(self, deals: list) -> int:
        """
        Sync closed trades from MT5 history to local DB.
        deals is a list of MT5 deal objects (entry == DEAL_ENTRY_OUT).
        Returns the number of updated records.
        """
        updated_count = 0
        now = datetime.now(timezone.utc).isoformat()
        with self._lock:
            conn = self._get_conn()
            try:
                for deal in deals:
                    # deal.position_id is often the same as the ticket of the position
                    ticket = deal.position_id
                    
                    # Check if it's still 'open' in DB
                    row = conn.execute(
                        "SELECT id FROM trades WHERE ticket=? AND status='open'", 
                        (ticket,)
                    ).fetchone()
                    
                    if row:
                        conn.execute(
                            """UPDATE trades SET status='closed',
                               close_price=?, pnl=?, closed_at=?
                               WHERE ticket=? AND status='open'""",
                            (deal.price, deal.profit, now, ticket),
                        )
                        updated_count += 1
                conn.commit()
            finally:
                conn.close()
        return updated_count

    def get_today_trades(self) -> List[Dict]:
        today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        with self._lock:
            conn = self._get_conn()
            try:
                rows = conn.execute(
                    "SELECT * FROM trades WHERE opened_at LIKE ? AND status != 'reset' "
                    "ORDER BY opened_at DESC",
                    (f"{today}%",),
                ).fetchall()
                return [dict(r) for r in rows]
            finally:
                conn.close()

    def reset_today_trades(self) -> None:
        today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        with self._lock:
            conn = self._get_conn()
            try:
                conn.execute(
                    "UPDATE trades SET status='reset' WHERE opened_at LIKE ?",
                    (f"{today}%",),
                )
                conn.commit()
                logger.info("Today's trades marked as reset in database")
            finally:
                conn.close()

    def get_weekly_trades(self) -> List[Dict]:
        week_ago = (
            datetime.now(timezone.utc) - timedelta(days=7)
        ).isoformat()
        with self._lock:
            conn = self._get_conn()
            try:
                rows = conn.execute(
                    "SELECT * FROM trades WHERE opened_at >= ? "
                    "ORDER BY opened_at DESC",
                    (week_ago,),
                ).fetchall()
                return [dict(r) for r in rows]
            finally:
                conn.close()

    # ── Signals ──────────────────────────────────────────────

    def log_signal(
        self, symbol: str, direction: str, entry_price: float,
        sl_price: float, tp1_price: float, tp2_price: float,
        rr_ratio: float, setup_score: float, setup_type: str,
        confidence: str, session: str, executed: bool = False,
        reason_rejected: str = "",
        steps_log: Optional[Dict] = None,
    ) -> int:
        now = datetime.now(timezone.utc).isoformat()
        steps_json = json.dumps(steps_log) if steps_log else ""
        with self._lock:
            conn = self._get_conn()
            try:
                cur = conn.execute(
                    """INSERT INTO signals
                       (symbol,direction,entry_price,sl_price,tp1_price,
                        tp2_price,rr_ratio,setup_score,setup_type,
                        confidence,session,executed,reason_rejected,
                        steps_log,created_at)
                       VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
                    (symbol, direction, entry_price, sl_price, tp1_price,
                     tp2_price, rr_ratio, setup_score, setup_type,
                     confidence, session, int(executed), reason_rejected,
                     steps_json, now),
                )
                conn.commit()
                return cur.lastrowid
            finally:
                conn.close()

    # ── Event Log ────────────────────────────────────────────

    def log_event(
        self, level: str, message: str, category: str = "general",
        symbol: str = "", details: str = "",
    ) -> None:
        now = datetime.now(timezone.utc).isoformat()
        with self._lock:
            conn = self._get_conn()
            try:
                conn.execute(
                    """INSERT INTO logs
                       (level,category,symbol,message,details,created_at)
                       VALUES (?,?,?,?,?,?)""",
                    (level, category, symbol, message, details, now),
                )
                conn.commit()
            finally:
                conn.close()

    def get_recent_logs(self, limit: int = 100) -> List[Dict]:
        with self._lock:
            conn = self._get_conn()
            try:
                rows = conn.execute(
                    "SELECT * FROM logs ORDER BY created_at DESC LIMIT ?",
                    (limit,),
                ).fetchall()
                return [dict(r) for r in rows]
            finally:
                conn.close()

    # ── Settings ─────────────────────────────────────────────

    def save_settings(self, config_dict: Dict[str, Any]) -> None:
        now = datetime.now(timezone.utc).isoformat()
        with self._lock:
            conn = self._get_conn()
            try:
                for key, value in config_dict.items():
                    conn.execute(
                        """INSERT OR REPLACE INTO settings
                           (key,value,updated_at) VALUES (?,?,?)""",
                        (key, json.dumps(value), now),
                    )
                conn.commit()
                logger.info("Settings saved to database")
            finally:
                conn.close()

    def load_settings(self) -> Dict[str, Any]:
        with self._lock:
            conn = self._get_conn()
            try:
                rows = conn.execute(
                    "SELECT key, value FROM settings"
                ).fetchall()
                result = {}
                for row in rows:
                    try:
                        result[row["key"]] = json.loads(row["value"])
                    except (json.JSONDecodeError, TypeError):
                        result[row["key"]] = row["value"]
                return result
            finally:
                conn.close()

    # ── Statistics ───────────────────────────────────────────

    def get_daily_stats(self) -> Dict:
        trades = self.get_today_trades()
        return self._compute_stats(trades)

    def get_weekly_stats(self) -> Dict:
        trades = self.get_weekly_trades()
        return self._compute_stats(trades)

    def get_unrealized_pnl(self, open_positions: list) -> float:
        """Sum the profit of live MT5 positions."""
        if not open_positions:
            return 0.0
        return round(sum(getattr(pos, "profit", 0.0) for pos in open_positions), 2)

    @staticmethod
    def _compute_stats(trades: List[Dict], open_positions: Optional[list] = None) -> Dict:
        closed = [t for t in trades if t["status"] == "closed"]
        wins = [t for t in closed if (t.get("pnl") or 0) > 0]
        losses = [t for t in closed if (t.get("pnl") or 0) <= 0]
        total_pnl = sum(t.get("pnl", 0) or 0 for t in closed)
        rr_vals = [t["rr_ratio"] for t in closed if t.get("rr_ratio")]

        # Count actual open trades (if MT5 positions are provided)
        if open_positions is not None:
            active_tickets = {pos.ticket for pos in open_positions}
            open_count = len([t for t in trades if t["status"] == "open" and t["ticket"] in active_tickets])
        else:
            open_count = len([t for t in trades if t["status"] == "open"])

        return {
            "total_trades": len(trades),
            "open_trades": open_count,
            "closed_trades": len(closed),
            "wins": len(wins),
            "losses": len(losses),
            "win_rate": (
                len(wins) / len(closed) * 100 if closed else 0.0
            ),
            "total_pnl": round(total_pnl, 2),
            "best_rr": round(max(rr_vals), 2) if rr_vals else 0.0,
            "avg_rr": (
                round(sum(rr_vals) / len(rr_vals), 2)
                if rr_vals else 0.0
            ),
        }
